version: "3"
services:
  db:
    image: postgres:latest
    container_name: databasex
    expose:
    - 5432
    ports:
      - 5432:5432
    environment:
         - POSTGRES_PASSWORD=admin
         - POSTGRES_USER=postgres
         - POSTGRES_DB=sample
    restart: unless-stopped

